name: shop_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.4
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.2.0
  shared_preferences: ^2.0.9
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
